### ISSUE TITLE
libneosurf not found

### ISSUE THREAD

**Issue by se7en-x230** [CobaltBSD/neosurf#1]
Arch linux
set runtime path of "/usr/local/lib/libneosurf.so  to ""

error loading shared lib ... no such file or ...

**Comment by CobaltBSD** [comment]
You should be able to fix this by adding `/usr/local/lib` to your `/etc/ld.so.conf` file. Alternatively, you can run `cmake .. -DCMAKE_INSTALL_PREFIX=/usr` so it installs in a place where your system can already find it instead

**Comment by se7en-x230** [comment]
Thanks new build instructions work.

Any chance to get it working with xorg?
