### ISSUE TITLE
Build from source failed due to openssl version?

### ISSUE THREAD

**Issue by Daeraxa** [CobaltBSD/neosurf#22]
```
~/s/neosurf $ cmake -B build -DCMAKE_INSTALL_PREFIX=/usr
yacc program found: bison
-- Configuring done (0.0s)
-- Generating done (0.0s)
-- Build files have been written to: /home/dae/sourcebuild/neosurf/build/contrib/libcss/gen_parser
gmake: Entering directory '/home/dae/sourcebuild/neosurf/build/contrib/libcss/gen_parser'
[100%] Built target gen_parser
gmake: Leaving directory '/home/dae/sourcebuild/neosurf/build/contrib/libcss/gen_parser'
CMake Error at src/CMakeLists.txt:41 (message):
  NeoSurf does not support OpenSSL 1.x.x

-- Configuring incomplete, errors occurred!
~/s/neosurf $ openssl version 
OpenSSL 3.0.9 30 May 2023 (Library: OpenSSL 3.0.9 30 May 2023)
```

Any ideas why it seems to be unhappy with the installed version of OpenSSL?

**Comment by CobaltBSD** [comment]
What distro were you using? Also, what does `pkg-config --modversion libssl` output?

**Comment by Daeraxa** [comment]
This is on Fedora 38, and the output is indeed a 1.x - 1.1.1q.

**Comment by mcirsta** [comment]
I think this can be closed as not supported. Fedora includes OpenSSL 3.x for more than a year now , since Fedora 36 launched on 2022-05-10. 
  I see no reason to support OpenSSL 1.x as all modern distros have switched to 3.x already for a while now.

**Comment by Daeraxa** [comment]
@mcirsta I don't think anybody was asking for 1.x to be supported? However OpenSSL 1.x is still being maintained and is present in LTS releases such as Ubuntu 20.04, Debian 10 in particular.

The issue turns out that something was causing a conflict between the `openssl-devel` versions which I discovered thanks to the output from the command provided by @CobaltBSD :

```sh
# sudo dnf install openssl-devel
...
Error: 
 Problem: problem with installed package openssl1.1-devel-1:1.1.1q-4.fc38.x86_64
  - package openssl1.1-devel-1:1.1.1q-4.fc38.x86_64 from @System conflicts with openssl-devel provided by openssl-devel-1:3.0.8-2.fc38.i686 from fedora
...
```

Ended up needing to remove `openssl1.1-devel` entirely in order to be able to install `openssl-devel` over it.

**Comment by mcirsta** [comment]
I worked on porting some stuff from OpenSSL 1.x to 3.x and I know there's a few differences. Normally you deal with them by just putting in some ifdefs.
 
Glad your problem was resolved, I was just saying that I'm not sure it's worth having 1.x support now but I'm not against it. As always the question is who will put in the work. I'd rather work on some other things related to the browser performance.

**Comment by Daeraxa** [comment]
> As always the question is who will put in the work.

And this is where I agree that I think you probably shouldn't bother supporting 1.x. If this was a big project that was already stable etc. then yeah, sure. Otherwise if somebody wants 1.x support then they can implement it themselves.

**Comment by Daeraxa** [comment]
I've made the above PR to mention 3.x in the readme for the dependencies. It doesn't "close" this issue so much (as that was already fixed and a weird fault with my system) but informs people in case they try to use 1.x (although I understand if you don't want to merge it as the error it gives is pretty clear when trying to use 1.x).
