### ISSUE TITLE
[Collaboration request] Simplify build process

### ISSUE THREAD

**Issue by nicolarevelant** [CobaltBSD/neosurf#27]
I would like to simplify the build process but currently I cannot understand the build process of the following libraries:

- libcss
- nsgenbind

If you explain how these libraries are compiled I can make a pull request keeping in mind that the goal is to simplify the build process and not to compile code during Cmake configuration.

**Comment by CobaltBSD** [comment]
nsgenbind is built during configure-time, and used to build the rest of neosurf. libcss generates a number of files using the libcss/src/parse/properties/parser_wrapper.py and libcss/select/select_generator.py scripts (the former of which builds libcss/gen_parser, which the script uses). These files are then built as part of libcss, like with any other libraries

It is quite unintuitive to implement in cmake. For that reason, I've started adding GNUmakefiles to provide a method of building that is simpler and much more straight-forward without the need for configure-time hacks.
