### ISSUE TITLE
[Arch] urlfilter no such file or directory

### ISSUE THREAD

**Issue by mebitek** [CobaltBSD/neosurf#5]
Just installed neosurf and I'm trying to open local html files (In fact I'm trying to use  neosurf as neomutt html mailcap reader)
with neosurf-vi I get
and I get this error:

```
starting urlfilter failed: No such file or directory
                             │Fatal: nsurl_create failed
```
with neosurf-gtk3 it works as expected

can you please help me?

**Comment by mebitek** [comment]
UPDATE: I find urlfilter in the src directory I've manually copied into my bin directory.
now I just 

```
get Fatal: nsurl_create failed
```

**Comment by mebitek** [comment]
UPDATE 2: I delete the urlfilter from bin directory and I open files with the prefix file://${FULL_PATH} and it seems to work
I need to try a zsh alias to add file prefix to the string if it is a local file

**Comment by CobaltBSD** [comment]
Both issues you described (urlfilter and nsurl_create) should be fixed in the latest commit.
