### ISSUE TITLE
libcss.so undefined references

### ISSUE THREAD

**Issue by i2** [CobaltBSD/neosurf#6]
Hi, on Ubuntu, I am trying to build this with both visurf and gtk3 frontends and towards the end of make, I get this:

```
[ 94%] Linking C executable neosurf-vi
/usr/bin/ld: ../contrib/libcss/libcss.so: undefined reference to `css__parse_border_left_width'
/usr/bin/ld: ../contrib/libcss/libcss.so: undefined reference to `css__parse_font_style'
.
.
.
/usr/bin/ld: ../contrib/libcss/libcss.so: undefined reference to `css__parse_empty_cells'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/neosurf-vi.dir/build.make:315: src/neosurf-vi] Error 1
make[1]: *** [CMakeFiles/Makefile2:562: src/CMakeFiles/neosurf-vi.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```
What is missing? Thanks!

**Comment by i2** [comment]
Looking at the other issue reported, I'd like to note that I did the modification suggested in [here](https://github.com/CobaltBSD/neosurf/issues/3#issuecomment-1544920304), but still same error!

**Comment by CobaltBSD** [comment]
> Looking at the other issue reported, I'd like to note that I did the modification suggested in [here](https://github.com/CobaltBSD/neosurf/issues/3#issuecomment-1544920304), but still same error!

Can you run these commands from a brand new build directory, and tell me if you get an error:
```sh
cmake -B contrib/libcss/gen_parser ../contrib/libcss/src/parse/properties/gen_parser
make -C contrib/libcss/gen_parser
mkdir contrib/libcss/properties
../contrib/libcss/src/parse/properties/parser_wrapper.sh contrib/libcss/properties contrib/libcss/gen_parser/gen_parser ../contrib/libcss/src/parse/properties/properties.gen
```

**Comment by i2** [comment]
Thanks! That did it.

For future reference, I did the following and it resolved the issue:

```
mkdir -v build
cd build
cmake -B contrib/libcss/gen_parser ../contrib/libcss/src/parse/properties/gen_parser
make -C contrib/libcss/gen_parser
mkdir contrib/libcss/properties
../contrib/libcss/src/parse/properties/parser_wrapper.sh contrib/libcss/properties contrib/libcss/gen_parser/gen_parser ../contrib/libcss/src/parse/properties/properties.gen
cmake .. -DCMAKE_INSTALL_PREFIX=/usr
```

**Comment by i2** [comment]
Mind you running `neosurf-vi` errors out with `Segmentation fault` but that's a whole new issue to be resolved.

**Comment by CobaltBSD** [comment]
Are you running it in Wayland?

**Comment by i2** [comment]
1. I suggest adding `flex bison libssl-dev` to the requirements

2. I gave it another try and here's what I found regarding `neosurf-vi`:

Ubuntu bare metal (both X11 and Wayland):
Fatal: Error connecting to Wayland display

Ubuntu WSL2:
Segmentation fault

Note:I have all the required packaged (` libwayland-dev` etc. installed).

**Comment by CobaltBSD** [comment]
Just to clarify, does neosurf-gtk3 work under the same conditions? I haven't tested neosurf in WSL2 myself although I wouldn't expect neosurf-vi to work, since it needs a Wayland compositor running. As for bare metal, this seems like an issue related to Wayland on your system. You are running neosurf-vi inside a Wayland compositor (e.g. labwc) right?

**Comment by i2** [comment]
1. neosurf-gtk3 works both in bare-metal and WSL2.
2. On bare-metal, I'm running neosurf-vi in Ubuntu Gnome Wayland.

**Comment by CobaltBSD** [comment]
> 2\. On bare-metal, I'm running neosurf-vi in Ubuntu Gnome Wayland.

What does `echo $WAYLAND_DISPLAY` output on your system?

**Comment by i2** [comment]
`wayland-0`

**Comment by CobaltBSD** [comment]
> `wayland-0`

Sorry, but after looking into this, it seems most likely to be an issue with Wayland on your machine. The error you described (resulting from [wl_display_connect](https://manpages.debian.org/experimental/libwayland-doc/wl_display_connect.3.en.html)) indicates that libwayland-client is unable to find where the Wayland socket is or connect to it, which it should be able to by default. I will keep an eye on this to see if other people report the same issue. If you want to further isolate the issue, you could try building `[wbg](https://codeberg.org/dnkl/wbg)` or some other simple Wayland-specific program from source to see if you get the same problem.
