### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by nicolarevelant** [CobaltBSD/neosurf#7]
The compilation failed due to the c flag that converts warnings to errors.
If I run "cmake --build . --target neosurf-gtk3" and then "cmake --build . --target neosurf-vi" instead of make (or cmake --build .) it works without warnings nor errors.

**Comment by CobaltBSD** [comment]
Can you tell me which warning specifically causes an error?

**Comment by CobaltBSD** [comment]
This should be fixed in the latest version
